<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit user
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "user/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmailaddress" class="col-sm-2 control-label">EmailAddress</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["emailAddress", "size" => 30, "class" => "form-control", "id" => "fieldEmailaddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRole" class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["role", "size" => 30, "class" => "form-control", "id" => "fieldRole"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValidationkey" class="col-sm-2 control-label">Validationkey</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["validationkey", "size" => 30, "class" => "form-control", "id" => "fieldValidationkey"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["status", "size" => 30, "class" => "form-control", "id" => "fieldStatus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedat" class="col-sm-2 control-label">Createdat</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["createdat", "size" => 30, "class" => "form-control", "id" => "fieldCreatedat"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedat" class="col-sm-2 control-label">Updatedat</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updatedat", "size" => 30, "class" => "form-control", "id" => "fieldUpdatedat"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
