<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search orderDetail
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["orderDetail/new", "Create orderDetail"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "orderDetail/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductid" class="col-sm-2 control-label">Productid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["productid", "type" => "number", "class" => "form-control", "id" => "fieldProductid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOrderid" class="col-sm-2 control-label">Orderid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["orderid", "type" => "number", "class" => "form-control", "id" => "fieldOrderid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSubtotal" class="col-sm-2 control-label">Subtotal</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["subtotal", "type" => "number", "class" => "form-control", "id" => "fieldSubtotal"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
