<nav class="navbar navbar-default navbar-fixed-top">
	<ul class="list-inline nav navbar-nav navbar-right">
		<li><a href="/shoppingCart/product/checkOUT/"><button id="checkOut" type="button" class="btn btn-primary navbar-btn center-block">Check Out</button></li>
		<li><button id="emptyCart" type="button" class="btn btn-primary navbar-btn center-block">Empty Cart</button></li>
		<li><span style="font-size:40px;margin-right:0px;" class="glyphicon glyphicon-shopping-cart navbar-btn"></span></li>
		<li><div class="navbar-text" id="cart" style="font-size:12pt;margin-left:0px;margin-right:0px;"><?php echo $totalItems;?><div></li>
		<li><div class="navbar-text" style="font-size:14pt;margin-left:0px;">Item(s)</div></li>
	</ul>
	 <ul class="nav navbar-nav navbar-left">
	  <li><a href="/shoppingCart/product/displayGrid"></a></li>
	  <li><a href="/shoppingCart/product/checkOut">Home</a></li>
      <li><a href="/shoppingCart/product/displayGrid">Shop</a></li>
      <li><a href="">about</a></li>
    </ul>
	 <ul class="nav navbar-nav navbar-leftS">
      <li><a href="/shoppingCart/user/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/shoppingCart/user/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
</nav>

<div style="padding-top:70px" class="container">
<?php $j=0;//set a counter for the number of columns in the grid col-sm-3 means 4 columns wide?>
<?php foreach($products as $product): ?>
	<?php if ($j==0) echo "<div class='row'>"; //if the counter is zero start a new row?>
	   <div class="col-sm-3">
		  <div class="panel panel-primary">  
			<div class="panel-heading"><?php echo $product->getName() ."  " . $product->getDescription();?></div>
			<div class="panel-body"><img style="width:80%;height:200px;" class="img-responsive center-block" 
				src="<?php echo $this->url->getBaseUri() . '/img/' . $product->getImage();?>"/></div>
			<div class="panel-footer">
				<button id="addItem" type="button" class="btn btn-default center-block addItem" value="<?php echo $product->getID();?>">Add To Cart</button>
			</div>
		  </div>
		</div>
	<?php $j++; if ($j==4) { echo "</div>"; $j=0;} //if we have 4 cols then close the div for the row and reset the counter?>
<?php endforeach; ?>
</div>
<script>
$(".bth,.addItem").click(function() {
	var total = parseInt($('#cart').text());
	var i=$(this).val();
	$('#cart').text(total);
	$.ajax({
	  type: "POST",
	  url: "/shoppingCart/product/addItem",
	  data: "productid=" + i,
	  dataType: "html",
	  success: function() {
		  total=total+1;
		  $('#cart').text(total);
	  },
	  error: function() {
		  alert("problem communicating with the server");
	  }
	});
});
$("#emptyCart").click(function() {
	$.ajax({
	  type: "get",
	  url: "/shoppingCart/product/emptyCart",
	  success: function() {
		  $('#cart').text(0);
	  },
	  error: function() {
		  alert("problem communicating with the server");
	  }
	});
});
</script>